api_platform:
  title: 'E-Com API'
  version: '1.0'
  formats:
    json: ['application/json']
    jsonld: ['application/ld+json']
  graphql:
    enabled: true
  doctrine:
    enabled: true
  defaults:
    pagination_enabled: true
    pagination_type: 'cursor'
    pagination_client_enabled: true
    pagination_client_items_per_page: true
    items_per_page: 20
    cache_headers:
      vary: ['Content-Type', 'Authorization']
    extra_properties:
      openapi_context:
        parameters:
          - in: query
            name: cursor
            schema: { type: string }
            description: 'Opaque cursor for pagination'
          - in: query
            name: limit
            schema: { type: integer }
            description: 'Limit number of items (max 200)'
          - in: query
            name: include_total
            schema: { type: boolean }
            description: 'Include total item count'
          - in: query
            name: page
            schema: { type: integer }
            description: 'Page number for page/limit mode'
          - in: query
            name: per_page
            schema: { type: integer }
            description: 'Items per page for page/limit mode'
  swagger:
    versions: [3]
