api_platform:
  title: 'E-Com API'
  version: '1.0'
  formats:
    json: ['application/json']
    jsonld: ['application/ld+json']
  doctrine:
    enabled: true
  defaults:
    pagination_enabled: true
    pagination_type: 'cursor'
    pagination_client_enabled: true
    pagination_client_items_per_page: true
    items_per_page: 20
    cache_headers:
      vary: ['Content-Type', 'Authorization']
  swagger:
    versions: [3]
