monolog:
  channels: ['api','security','doctrine','messenger','http_client','event']
  handlers:
    main:
      type: fingers_crossed
      action_level: warning
      handler: main_buffered
      channels: ["!event"]
    main_buffered:
      type: stream
      path: "php://stdout"
      level: debug
      formatter: monolog.formatter.json
      channels: ["!event"]
    api:
      type: stream
      path: "php://stdout"
      level: info
      formatter: monolog.formatter.json
      channels: ["api"]
    security:
      type: stream
      path: "php://stderr"
      level: notice
      formatter: monolog.formatter.json
      channels: ["security"]
    doctrine:
      type: stream
      path: "php://stdout"
      level: notice
      formatter: monolog.formatter.json
      channels: ["doctrine"]
    messenger:
      type: stream
      path: "php://stdout"
      level: info
      formatter: monolog.formatter.json
      channels: ["messenger"]
    http_client:
      type: stream
      path: "php://stdout"
      level: error
      formatter: monolog.formatter.json
      channels: ["http_client"]
    event:
      type: stream
      path: "php://stdout"
      level: info
      formatter: monolog.formatter.json
      channels: ["event"]
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event","!doctrine"]
  processors:
    - 'App\\Shared\\Logging\\RequestContextProcessor'
    - 'App\\Shared\\Logging\\SanitizeContextProcessor'
