nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['https://admin.example.com', 'http://localhost:3000']
    allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
    expose_headers: ['Link', 'X-Request-Id']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    max_age: 3600
  paths:
    '^/': ~
