security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      id: App\Infrastructure\Security\UserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api:
      pattern: ^/(api|graphql)
      stateless: true
      provider: app_user_provider
      lazy: true
      jwt: ~

  access_control:
    - { path: ^/(api|graphql), roles: PUBLIC_ACCESS, methods: [GET], rate_limiter: api_anonymous }
    - { path: ^/(api|graphql), roles: IS_AUTHENTICATED_FULLY, rate_limiter: api_authenticated }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
